# Generated by Django 5.2.5 on 2025-10-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_department_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
